/**
 * Registers every built-in page-builder component type once.
 *
 * Called from `lib/page-builder/registry-init.ts` (auto-imported by the editor
 * and the runtime renderer). Idempotent: re-running is safe.
 *
 * Type strings are GAB-canonical so layouts can be exchanged with GAB Core
 * without remapping. Legacy `atom_*` / `mol_*` / `org_*` ids from the original
 * Showcase manifest are kept as aliases so existing pages continue to render.
 */

import {
  pageComponentRegistry,
  type PageComponentDefinition,
} from './page-component-registry';

let registered = false;

export function registerBuiltins(): void {
  if (registered) return;
  registered = true;

  const defs: PageComponentDefinition[] = [
    // ─── Layout / Containers ──────────────────────────────────────────
    {
      type: 'spacer',
      label: 'Spacer',
      category: 'layout',
      icon: 'StretchVertical',
      description: 'Vertical empty space',
      aliases: ['pb_spacer'],
      defaultProps: { height: 24 },
      props: [
        { key: 'height', label: 'Height (px)', editor: 'number', defaultValue: 24 },
      ],
      dataShape: 'none',
    },
    {
      type: 'divider',
      label: 'Divider',
      category: 'layout',
      icon: 'Minus',
      aliases: ['atom_separator'],
      defaultProps: {},
      props: [],
      dataShape: 'none',
    },
    {
      type: 'card',
      label: 'Card',
      category: 'layout',
      icon: 'Square',
      aliases: ['mol_card'],
      defaultProps: { title: 'Card', description: '' },
      props: [
        { key: 'title', label: 'Title', editor: 'string', defaultValue: 'Card' },
        { key: 'description', label: 'Description', editor: 'multiline', span: 2 },
      ],
      dataShape: 'none',
      isContainer: true,
    },
    {
      type: 'tabs-container',
      label: 'Tabs',
      category: 'containers',
      icon: 'Folder',
      aliases: ['mol_tabs'],
      defaultProps: { tabLabels: 'Overview, Details' },
      props: [
        {
          key: 'tabLabels',
          label: 'Tab labels (comma-sep)',
          editor: 'list',
          defaultValue: 'Overview, Details',
          span: 2,
        },
      ],
      dataShape: 'none',
      isContainer: true,
    },
    {
      type: 'conditional-container',
      label: 'Conditional',
      category: 'containers',
      icon: 'GitBranch',
      defaultProps: { showWhen: '' },
      props: [
        {
          key: 'showWhen',
          label: 'Show when (selection key)',
          editor: 'string',
          description: 'Renders children only when a record is selected on the page.',
          span: 2,
        },
      ],
      dataShape: 'none',
      isContainer: true,
    },
    {
      type: 'collapsible-section',
      label: 'Collapsible',
      category: 'containers',
      icon: 'ChevronsDownUp',
      aliases: ['mol_accordion'],
      defaultProps: { itemTitle: 'Section', defaultOpen: true },
      props: [
        { key: 'itemTitle', label: 'Title', editor: 'string', defaultValue: 'Section' },
        { key: 'defaultOpen', label: 'Open by default', editor: 'boolean', defaultValue: true },
      ],
      dataShape: 'none',
      isContainer: true,
    },

    // ─── Content / typography ─────────────────────────────────────────
    {
      type: 'text-block',
      label: 'Text',
      category: 'content',
      icon: 'Text',
      aliases: ['atom_text', 'pb_text_block'],
      defaultProps: { content: 'Body text', size: 'md' },
      props: [
        { key: 'content', label: 'Text', editor: 'multiline', defaultValue: 'Body text', span: 2 },
        {
          key: 'size',
          label: 'Size',
          editor: 'select',
          defaultValue: 'md',
          options: [
            { value: 'xs', label: 'XS' },
            { value: 'sm', label: 'SM' },
            { value: 'md', label: 'MD' },
            { value: 'lg', label: 'LG' },
          ],
        },
      ],
      dataShape: 'none',
    },
    {
      type: 'heading',
      label: 'Heading',
      category: 'content',
      icon: 'Heading',
      aliases: ['atom_heading'],
      defaultProps: { children: 'Section title', level: 'h2' },
      props: [
        { key: 'children', label: 'Text', editor: 'string', defaultValue: 'Section title', span: 2 },
        {
          key: 'level',
          label: 'Level',
          editor: 'select',
          defaultValue: 'h2',
          options: [
            { value: 'h1', label: 'H1' },
            { value: 'h2', label: 'H2' },
            { value: 'h3', label: 'H3' },
            { value: 'h4', label: 'H4' },
          ],
        },
      ],
      dataShape: 'none',
    },
    {
      type: 'page-header',
      label: 'Page header',
      category: 'content',
      icon: 'PanelTop',
      aliases: ['mol_page_header'],
      defaultProps: { title: 'Page', subtitle: '' },
      props: [
        { key: 'title', label: 'Title', editor: 'string', defaultValue: 'Page' },
        { key: 'subtitle', label: 'Subtitle', editor: 'string' },
      ],
      dataShape: 'none',
    },
    {
      type: 'hero',
      label: 'Hero',
      category: 'content',
      icon: 'Image',
      aliases: ['mol_hero'],
      defaultProps: { title: 'Hero', subtitle: 'Subtitle' },
      props: [
        { key: 'title', label: 'Title', editor: 'string', defaultValue: 'Hero' },
        { key: 'subtitle', label: 'Subtitle', editor: 'string' },
      ],
      dataShape: 'none',
    },
    {
      type: 'alert-block',
      label: 'Alert',
      category: 'content',
      icon: 'AlertCircle',
      aliases: ['mol_alert'],
      defaultProps: {
        title: 'Notice',
        children: 'Message',
        variant: 'info',
      },
      props: [
        { key: 'title', label: 'Title', editor: 'string', defaultValue: 'Notice' },
        { key: 'children', label: 'Message', editor: 'multiline', span: 2 },
        {
          key: 'variant',
          label: 'Variant',
          editor: 'select',
          defaultValue: 'info',
          options: [
            { value: 'info', label: 'Info' },
            { value: 'success', label: 'Success' },
            { value: 'warning', label: 'Warning' },
            { value: 'error', label: 'Error' },
          ],
        },
      ],
      dataShape: 'none',
    },
    {
      type: 'badge',
      label: 'Badge',
      category: 'content',
      icon: 'Tag',
      aliases: ['atom_badge'],
      defaultProps: { children: 'Label' },
      props: [{ key: 'children', label: 'Text', editor: 'string', defaultValue: 'Label' }],
      dataShape: 'none',
    },
    {
      type: 'chip',
      label: 'Chip',
      category: 'content',
      icon: 'Tag',
      aliases: ['atom_chip'],
      defaultProps: { children: 'Tag' },
      props: [{ key: 'children', label: 'Text', editor: 'string', defaultValue: 'Tag' }],
      dataShape: 'none',
    },
    {
      type: 'banner',
      label: 'Banner',
      category: 'content',
      icon: 'Megaphone',
      aliases: ['mol_banner'],
      defaultProps: { children: 'Banner message' },
      props: [{ key: 'children', label: 'Message', editor: 'multiline', span: 2 }],
      dataShape: 'none',
    },
    {
      type: 'empty-state',
      label: 'Empty state',
      category: 'content',
      icon: 'Inbox',
      aliases: ['mol_empty_state'],
      defaultProps: { title: 'No data', description: '' },
      props: [
        { key: 'title', label: 'Title', editor: 'string', defaultValue: 'No data' },
        { key: 'description', label: 'Description', editor: 'multiline', span: 2 },
      ],
      dataShape: 'none',
    },
    {
      type: 'label-value',
      label: 'Label / value',
      category: 'content',
      icon: 'AlignLeft',
      aliases: ['mol_label_value'],
      defaultProps: { label: 'Field', value: '—' },
      props: [
        { key: 'label', label: 'Label', editor: 'string', defaultValue: 'Field' },
        { key: 'value', label: 'Value', editor: 'string', defaultValue: '—' },
      ],
      dataShape: 'none',
    },
    {
      type: 'code',
      label: 'Code',
      category: 'content',
      icon: 'Code',
      aliases: ['atom_code'],
      defaultProps: { children: 'key' },
      props: [{ key: 'children', label: 'Text', editor: 'string', defaultValue: 'key' }],
      dataShape: 'none',
    },

    // ─── Buttons / actions ────────────────────────────────────────────
    {
      type: 'page-button',
      label: 'Button',
      category: 'content',
      icon: 'MousePointerClick',
      aliases: ['atom_button'],
      defaultProps: { children: 'Button', variant: 'primary' },
      props: [
        { key: 'children', label: 'Label', editor: 'string', defaultValue: 'Button' },
        {
          key: 'variant',
          label: 'Variant',
          editor: 'select',
          defaultValue: 'primary',
          options: [
            { value: 'primary', label: 'Primary' },
            { value: 'secondary', label: 'Secondary' },
            { value: 'outline', label: 'Outline' },
            { value: 'ghost', label: 'Ghost' },
            { value: 'destructive', label: 'Destructive' },
          ],
        },
        { key: 'href', label: 'Link href (optional)', editor: 'string', span: 2 },
      ],
      dataShape: 'none',
    },
    {
      type: 'page-link',
      label: 'Link',
      category: 'navigation',
      icon: 'Link',
      aliases: ['atom_uilink'],
      defaultProps: { children: 'Link', href: '#' },
      props: [
        { key: 'children', label: 'Text', editor: 'string', defaultValue: 'Link' },
        { key: 'href', label: 'URL', editor: 'string', defaultValue: '#' },
      ],
      dataShape: 'none',
    },
    {
      type: 'breadcrumbs',
      label: 'Breadcrumbs',
      category: 'navigation',
      icon: 'ChevronRight',
      aliases: ['mol_breadcrumbs'],
      defaultProps: { items: 'Home, Here' },
      props: [
        { key: 'items', label: 'Items (comma-sep)', editor: 'list', defaultValue: 'Home, Here', span: 2 },
      ],
      dataShape: 'none',
    },
    {
      type: 'pagination',
      label: 'Pagination',
      category: 'navigation',
      icon: 'ChevronRight',
      aliases: ['mol_pagination'],
      defaultProps: { page: 1, pageCount: 1 },
      props: [
        { key: 'page', label: 'Current page', editor: 'number', defaultValue: 1 },
        { key: 'pageCount', label: 'Total pages', editor: 'number', defaultValue: 1 },
      ],
      dataShape: 'none',
    },

    // ─── Form atoms (read-only previews on page canvas) ───────────────
    {
      type: 'form-input',
      label: 'Input',
      category: 'forms',
      icon: 'Type',
      aliases: ['atom_input'],
      defaultProps: { placeholder: 'Type…' },
      props: [{ key: 'placeholder', label: 'Placeholder', editor: 'string' }],
      dataShape: 'none',
    },
    {
      type: 'form-textarea',
      label: 'Textarea',
      category: 'forms',
      icon: 'AlignLeft',
      aliases: ['atom_textarea'],
      defaultProps: { placeholder: '…' },
      props: [{ key: 'placeholder', label: 'Placeholder', editor: 'string' }],
      dataShape: 'none',
    },
    {
      type: 'form-select',
      label: 'Select',
      category: 'forms',
      icon: 'ChevronDown',
      aliases: ['atom_select'],
      defaultProps: { placeholder: 'Select' },
      props: [{ key: 'placeholder', label: 'Placeholder', editor: 'string' }],
      dataShape: 'none',
    },
    {
      type: 'form-checkbox',
      label: 'Checkbox',
      category: 'forms',
      icon: 'CheckSquare',
      aliases: ['atom_checkbox'],
      defaultProps: { label: 'Option' },
      props: [{ key: 'label', label: 'Label', editor: 'string', defaultValue: 'Option' }],
      dataShape: 'none',
    },
    {
      type: 'form-switch',
      label: 'Switch',
      category: 'forms',
      icon: 'ToggleRight',
      aliases: ['atom_switch'],
      defaultProps: { label: 'Enable' },
      props: [{ key: 'label', label: 'Label', editor: 'string', defaultValue: 'Enable' }],
      dataShape: 'none',
    },
    {
      type: 'dynamic-form',
      label: 'Form embed',
      category: 'forms',
      icon: 'FormInput',
      aliases: ['org_dynamic_form'],
      defaultProps: { formId: '' },
      props: [
        {
          key: 'formId',
          label: 'Form ID',
          editor: 'string',
          description: 'Embeds a form. Set the form id for this app.',
          span: 2,
        },
      ],
      dataShape: 'none',
      featureFlag: 'app.forms',
    },

    // ─── Data widgets ─────────────────────────────────────────────────
    // Every widget here binds to records/scalar from a table and is hidden
    // when the tables module is off. Charts further depend on `app.reports`.
    {
      type: 'metric-card',
      label: 'Metric card',
      category: 'data',
      icon: 'Activity',
      aliases: ['mol_metric_card'],
      featureFlag: 'app.tables',
      defaultProps: { label: 'KPI', value: '0', aggregation: 'count' },
      props: [
        { key: 'label', label: 'Label', editor: 'string', defaultValue: 'KPI' },
        {
          key: 'value',
          label: 'Static value (when no binding)',
          editor: 'string',
          defaultValue: '0',
        },
        {
          key: 'aggregation',
          label: 'Aggregation',
          editor: 'select',
          defaultValue: 'count',
          options: [
            { value: 'count', label: 'Count of records' },
            { value: 'sum', label: 'Sum of field' },
            { value: 'avg', label: 'Average of field' },
            { value: 'min', label: 'Minimum of field' },
            { value: 'max', label: 'Maximum of field' },
            { value: 'first', label: 'First record value' },
          ],
        },
        {
          key: 'valueField',
          label: 'Field to aggregate',
          editor: 'string',
          description: 'Required for sum/avg/min/max/first.',
          visibleWhen: (p) => p.aggregation !== 'count',
        },
      ],
      dataShape: 'scalar',
    },
    {
      type: 'data-table',
      label: 'Data table',
      category: 'data',
      icon: 'Table',
      aliases: ['org_data_grid'],
      featureFlag: 'app.tables',
      defaultProps: { title: 'Records', pageSize: 10 },
      props: [
        { key: 'title', label: 'Title', editor: 'string', defaultValue: 'Records' },
        { key: 'pageSize', label: 'Rows per page', editor: 'number', defaultValue: 10 },
      ],
      dataShape: 'records',
      defaultColSpan: 2,
    },
    {
      type: 'filter-builder',
      label: 'Filter builder',
      category: 'data',
      icon: 'Filter',
      aliases: ['org_filter_builder'],
      featureFlag: 'app.tables',
      defaultProps: {},
      props: [],
      dataShape: 'none',
    },
    {
      type: 'detail-header',
      label: 'Detail header',
      category: 'data',
      icon: 'PanelTop',
      aliases: ['org_detail_header'],
      featureFlag: 'app.tables',
      defaultProps: { title: 'Record', titleField: 'name' },
      props: [
        { key: 'title', label: 'Title (when unbound)', editor: 'string', defaultValue: 'Record' },
        { key: 'titleField', label: 'Title field', editor: 'string', defaultValue: 'name' },
        { key: 'descriptionField', label: 'Description field', editor: 'string' },
        {
          key: 'metadataFields',
          label: 'Metadata fields',
          editor: 'string',
          description: 'Comma-separated list, e.g. "status,owner,priority".',
          span: 2,
        },
      ],
      dataShape: 'record',
    },
    {
      type: 'kanban-board',
      label: 'Kanban',
      category: 'data',
      icon: 'Columns3',
      aliases: ['org_kanban'],
      featureFlag: 'app.tables',
      defaultProps: { columnField: 'status', titleField: 'name' },
      props: [
        { key: 'columnField', label: 'Group by field', editor: 'string', defaultValue: 'status' },
        { key: 'titleField', label: 'Card title field', editor: 'string', defaultValue: 'name' },
        { key: 'descriptionField', label: 'Card description field', editor: 'string' },
      ],
      dataShape: 'records',
    },
    {
      type: 'gantt-chart',
      label: 'Gantt',
      category: 'data',
      icon: 'BarChart2',
      aliases: ['org_gantt'],
      featureFlag: 'app.tables',
      defaultProps: {},
      props: [],
      dataShape: 'records',
    },
    {
      type: 'timeline',
      label: 'Timeline',
      category: 'data',
      icon: 'List',
      aliases: ['org_timeline'],
      featureFlag: 'app.tables',
      defaultProps: { titleField: 'name', dateField: 'created_at' },
      props: [
        { key: 'titleField', label: 'Title field', editor: 'string', defaultValue: 'name' },
        { key: 'dateField', label: 'Date field', editor: 'string', defaultValue: 'created_at' },
        { key: 'descriptionField', label: 'Description field', editor: 'string' },
      ],
      dataShape: 'records',
    },
    {
      type: 'widget-grid',
      label: 'Widget grid',
      category: 'layout',
      icon: 'LayoutGrid',
      aliases: ['org_widget_grid'],
      defaultProps: { columns: 2 },
      props: [
        { key: 'columns', label: 'Columns', editor: 'number', defaultValue: 2 },
      ],
      dataShape: 'none',
    },

    // ─── Charts ───────────────────────────────────────────────────────
    {
      type: 'chart',
      label: 'Chart',
      category: 'charts',
      icon: 'BarChart3',
      aliases: ['org_chart_card'],
      featureFlag: 'app.reports',
      defaultProps: { title: 'Chart', kind: 'bar', dataKey: 'value' },
      props: [
        { key: 'title', label: 'Title', editor: 'string', defaultValue: 'Chart' },
        {
          key: 'kind',
          label: 'Type',
          editor: 'select',
          defaultValue: 'bar',
          options: [
            { value: 'bar', label: 'Bar' },
            { value: 'line', label: 'Line' },
            { value: 'area', label: 'Area' },
            { value: 'pie', label: 'Pie' },
          ],
        },
        { key: 'dataKey', label: 'Value field', editor: 'string', defaultValue: 'value' },
        { key: 'labelKey', label: 'Label field', editor: 'string', defaultValue: 'name' },
      ],
      dataShape: 'records',
    },

    // ─── Media ────────────────────────────────────────────────────────
    {
      type: 'image',
      label: 'Image',
      category: 'media',
      icon: 'Image',
      aliases: ['pb_image'],
      defaultProps: { src: '/next.svg', alt: '' },
      props: [
        { key: 'src', label: 'Source URL', editor: 'string', defaultValue: '/next.svg', span: 2 },
        { key: 'alt', label: 'Alt text', editor: 'string', span: 2 },
      ],
      dataShape: 'none',
    },
    {
      type: 'iframe-embed',
      label: 'IFrame embed',
      category: 'media',
      icon: 'ExternalLink',
      defaultProps: { src: '', height: 400 },
      props: [
        { key: 'src', label: 'URL', editor: 'string', span: 2 },
        { key: 'height', label: 'Height (px)', editor: 'number', defaultValue: 400 },
      ],
      dataShape: 'none',
    },
    {
      type: 'avatar',
      label: 'Avatar',
      category: 'media',
      icon: 'User',
      aliases: ['atom_avatar'],
      defaultProps: { fallback: 'A' },
      props: [
        { key: 'fallback', label: 'Initials', editor: 'string', defaultValue: 'A' },
        { key: 'src', label: 'Image URL', editor: 'string' },
      ],
      dataShape: 'none',
    },
    {
      type: 'spinner',
      label: 'Spinner',
      category: 'content',
      icon: 'Loader',
      aliases: ['atom_spinner'],
      defaultProps: {},
      props: [],
      dataShape: 'none',
    },
    {
      type: 'progress',
      label: 'Progress',
      category: 'content',
      icon: 'Loader',
      aliases: ['atom_progress'],
      defaultProps: { value: 50 },
      props: [{ key: 'value', label: 'Value (0-100)', editor: 'number', defaultValue: 50 }],
      dataShape: 'none',
    },

    // ─── Other organisms ──────────────────────────────────────────────
    {
      type: 'footer',
      label: 'Footer',
      category: 'layout',
      icon: 'Minus',
      aliases: ['org_footer'],
      defaultProps: { legalText: '' },
      props: [{ key: 'legalText', label: 'Legal text', editor: 'string', span: 2 }],
      dataShape: 'none',
    },
    {
      type: 'ai-disclaimer',
      label: 'AI disclaimer',
      category: 'content',
      icon: 'Info',
      aliases: ['org_ai_disclaimer'],
      defaultProps: {},
      props: [],
      dataShape: 'none',
    },
    {
      type: 'location-map',
      label: 'Location map',
      category: 'media',
      icon: 'MapPin',
      aliases: ['org_location_map'],
      defaultProps: {},
      props: [],
      dataShape: 'records',
    },
  ];

  pageComponentRegistry.registerAll(defs);
}
