'use client';

/**
 * ConvertToComponentWizard — extracts a single page block into a new
 * app-scoped custom component (gated by `pageBuilder.convertToComponent`).
 *
 * Flow:
 *   1. Naming      — name, description, icon, key derived from the name.
 *   2. Prop extract — heuristically classify each entry on `block.props`
 *                     as string/number/boolean/json; user can rename
 *                     labels and uncheck props they don't want exposed.
 *   3. Confirm      — calls `createCustomComponentAction` and asks the
 *                     parent to swap the block's `type` to `custom:<key>`,
 *                     keeping the block's id, position, and original
 *                     props as the new component's `defaultProps`.
 *
 * Code generation is intentionally a stub — the user finishes the
 * component in the existing custom-component editor afterwards. This
 * mirrors GAB Core's behavior and avoids brittle source-from-block
 * synthesis in the boilerplate.
 *
 * Removal recipe: flip `pageBuilder.convertToComponent` off OR delete
 * this file + the menu entry in PageEditorClient. Existing converted
 * components keep working; only the conversion entrypoint disappears.
 */

import { useMemo, useState, useTransition } from 'react';
import { Button, Input, Label, Text } from '@/components/ui/atoms';
import { Modal } from '@/components/ui/molecules';
import { createCustomComponentAction } from '@/app/actions/custom-components';
import { customTypeFor } from '@/lib/page-builder/register-custom';
import type { PageComponent } from '@/lib/core/ports/pages.repository';
import { cn } from '@/lib/utils';

export type ExtractedPropType = 'string' | 'number' | 'boolean' | 'json';

interface ExtractedProp {
  key: string;
  label: string;
  type: ExtractedPropType;
  defaultValue: unknown;
  exposed: boolean;
}

export interface ConvertToComponentWizardProps {
  appId: string;
  block: PageComponent | null;
  pageKey?: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /**
   * Called once the new component is created. Parent should patch the
   * page layout by setting the block's `type` to `customTypeFor(key)`
   * and its `props` to `defaultProps`.
   */
  onConverted: (args: {
    blockId: string;
    newType: string;
    defaultProps: Record<string, unknown>;
  }) => void;
}

function inferType(value: unknown): ExtractedPropType {
  if (typeof value === 'string') return 'string';
  if (typeof value === 'number') return 'number';
  if (typeof value === 'boolean') return 'boolean';
  return 'json';
}

function slugifyKey(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 64);
}

function generateStubCode(componentName: string, props: ExtractedProp[]): string {
  const exposed = props.filter((p) => p.exposed);
  const propList = exposed.map((p) => p.key).join(', ');
  const previewBody = exposed.length
    ? exposed
        .map(
          (p) =>
            `        <li><code>${p.key}</code>: <code>{String(${p.key})}</code></li>`,
        )
        .join('\n')
    : '        <li>No props extracted. Edit me!</li>';
  return `// ${componentName} — generated by Convert to Component
// Replace this stub with your real implementation. The page DSL
// passes the props listed below; data binding (if any) reaches you
// through the standard \`data\` prop.

export default function ${componentName.replace(/[^A-Za-z0-9]/g, '') || 'Component'}({ ${propList} }) {
  return (
    <div className="rounded border border-dashed p-4">
      <strong>${componentName}</strong>
      <ul className="mt-2 text-xs">
${previewBody}
      </ul>
    </div>
  );
}
`;
}

export function ConvertToComponentWizard({
  appId,
  block,
  pageKey,
  open,
  onOpenChange,
  onConverted,
}: ConvertToComponentWizardProps) {
  const [step, setStep] = useState<1 | 2 | 3>(1);
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [icon, setIcon] = useState('Box');
  const [props, setProps] = useState<ExtractedProp[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [isCreating, startCreate] = useTransition();

  const initialProps = useMemo<ExtractedProp[]>(() => {
    if (!block) return [];
    return Object.entries(block.props ?? {}).map(([key, value]) => ({
      key,
      label: key,
      type: inferType(value),
      defaultValue: value,
      exposed: true,
    }));
  }, [block]);

  // (Re)seed local state whenever the dialog opens for a new block.
  useMemo(() => {
    if (!open) return;
    setStep(1);
    setError(null);
    setName(block?.type ? toFriendlyName(block.type) : '');
    setDescription('');
    setIcon('Box');
    setProps(initialProps);
  }, [open, block, initialProps]);

  if (!block) return null;

  const trimmedName = name.trim();
  const componentKey = slugifyKey(trimmedName);
  const canAdvanceFromNaming = trimmedName.length > 0 && componentKey.length > 0;

  const togglePropExposed = (key: string) =>
    setProps((prev) =>
      prev.map((p) => (p.key === key ? { ...p, exposed: !p.exposed } : p)),
    );
  const renameProp = (key: string, label: string) =>
    setProps((prev) => prev.map((p) => (p.key === key ? { ...p, label } : p)));

  const create = () => {
    setError(null);
    startCreate(async () => {
      const exposed = props.filter((p) => p.exposed);
      const propsSchema = {
        fields: exposed.map((p) => ({
          key: p.key,
          label: p.label || p.key,
          type: p.type,
        })),
      };
      const defaultProps = Object.fromEntries(
        exposed.map((p) => [p.key, p.defaultValue]),
      );

      const res = await createCustomComponentAction(appId, {
        name: trimmedName,
        description: description.trim() || undefined,
        icon,
        code: generateStubCode(trimmedName, props),
        propsSchema,
        defaultProps,
        ...(pageKey ? { sourcePageKey: pageKey } : {}),
      });
      if (!res.success || !res.data) {
        setError(res.error ?? 'Failed to create component.');
        return;
      }
      onConverted({
        blockId: block.id,
        newType: customTypeFor(res.data.key),
        defaultProps,
      });
      onOpenChange(false);
    });
  };

  return (
    <Modal
      open={open}
      onOpenChange={onOpenChange}
      title="Convert to component"
      description={`Step ${step} of 3 — extract this block into a reusable component.`}
      size="lg"
    >
      <div className="space-y-4">
        {step === 1 && (
          <div className="space-y-3">
            <FieldRow>
              <Label htmlFor="cc-name">Component name</Label>
              <Input
                id="cc-name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="e.g. Health scorecard"
              />
              {trimmedName && (
                <Text size="xs" color="muted">
                  Stored key: <code>{componentKey}</code>
                </Text>
              )}
            </FieldRow>
            <FieldRow>
              <Label htmlFor="cc-desc">Description (optional)</Label>
              <Input
                id="cc-desc"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="What does this component do?"
              />
            </FieldRow>
            <FieldRow>
              <Label htmlFor="cc-icon">Lucide icon</Label>
              <Input
                id="cc-icon"
                value={icon}
                onChange={(e) => setIcon(e.target.value)}
                placeholder="Box"
              />
            </FieldRow>
          </div>
        )}

        {step === 2 && (
          <div className="space-y-2">
            <Text size="sm">
              Choose which props to expose. Unchecked props are hard-coded
              into the component&apos;s starter code.
            </Text>
            {props.length === 0 ? (
              <Text size="sm" color="muted">
                This block has no props to extract. You can still convert it.
              </Text>
            ) : (
              <ul className="divide-y divide-border rounded border border-border">
                {props.map((p) => (
                  <li
                    key={p.key}
                    className="px-3 py-2 flex items-center gap-3"
                  >
                    <input
                      id={`pp-${p.key}`}
                      type="checkbox"
                      checked={p.exposed}
                      onChange={() => togglePropExposed(p.key)}
                      className="h-4 w-4"
                    />
                    <div className="flex-1 min-w-0 grid grid-cols-3 gap-2">
                      <code className="truncate text-xs font-mono">
                        {p.key}
                      </code>
                      <Input
                        value={p.label}
                        onChange={(e) => renameProp(p.key, e.target.value)}
                        placeholder={p.key}
                        aria-label={`Label for ${p.key}`}
                      />
                      <span
                        className={cn(
                          'inline-flex items-center justify-center text-[10px] uppercase tracking-wide px-1.5 py-0.5 rounded bg-muted text-muted-foreground',
                        )}
                      >
                        {p.type}
                      </span>
                    </div>
                  </li>
                ))}
              </ul>
            )}
          </div>
        )}

        {step === 3 && (
          <div className="space-y-3">
            <Text size="sm">Ready to create:</Text>
            <ul className="space-y-1 text-sm">
              <li>
                <strong>{trimmedName}</strong>{' '}
                <code className="text-xs">({componentKey})</code>
              </li>
              <li>
                {props.filter((p) => p.exposed).length} prop
                {props.filter((p) => p.exposed).length === 1 ? '' : 's'}{' '}
                exposed
              </li>
              <li>
                Block <code>{block.type}</code> will become{' '}
                <code>custom:{componentKey}</code>
              </li>
            </ul>
            <Text size="xs" color="muted">
              You&apos;ll be able to edit the component&apos;s code in App
              settings → Custom components after this finishes.
            </Text>
            {error && (
              <Text size="sm" className="text-danger-text">
                {error}
              </Text>
            )}
          </div>
        )}

        <div className="flex justify-between gap-2 pt-2 border-t border-border">
          <Button
            type="button"
            variant="outline"
            onClick={() => (step > 1 ? setStep((step - 1) as 1 | 2) : onOpenChange(false))}
          >
            {step === 1 ? 'Cancel' : 'Back'}
          </Button>
          {step < 3 ? (
            <Button
              type="button"
              onClick={() => setStep((step + 1) as 2 | 3)}
              disabled={step === 1 && !canAdvanceFromNaming}
            >
              Next
            </Button>
          ) : (
            <Button type="button" onClick={create} disabled={isCreating}>
              {isCreating ? 'Creating…' : 'Create component'}
            </Button>
          )}
        </div>
      </div>
    </Modal>
  );
}

function FieldRow({ children }: { children: React.ReactNode }) {
  return <div className="space-y-1.5">{children}</div>;
}

/** "metric-card" → "Metric card", "custom:foo" → "Foo". */
function toFriendlyName(type: string): string {
  const tail = type.startsWith('custom:') ? type.slice(7) : type;
  const words = tail.replace(/[-_]+/g, ' ').trim();
  return words.charAt(0).toUpperCase() + words.slice(1);
}
