import 'server-only';
import type {
  IOCRPort,
  OCRJobHandle,
  OCRJobStatus,
  OCRResult,
} from '../../ports/ocr.port';
import { OCRServiceError } from '../../ports/ocr.port';

/**
 * Mock OCR adapter — simulates the real three-call lifecycle against
 * in-memory state so dev flows exercise the same client polling code.
 *
 *   startJob  → creates a fake jobId, records a start timestamp.
 *   getStatus → PENDING briefly, then PROCESSING, then COMPLETED after
 *               PROCESSING_DURATION_MS.
 *   getResult → returns canned extracted text.
 */

const PENDING_DURATION_MS = 500;
const PROCESSING_DURATION_MS = 3_000;

interface MockJob {
  fileName: string;
  startedAt: number;
}

const MOCK_FULL_TEXT = [
  'NOTICE OF AWARD',
  'Award Number: MOCK-2026-0001',
  'Recipient: Mock City Department of Public Works',
  'Federal Agency: U.S. Department of Mock Affairs',
  'CFDA Number: 99.999',
  'Award Amount: $1,250,000.00',
  'Period of Performance: 2026-01-01 through 2026-12-31',
  '',
  'This is canned OCR output generated by the mock adapter for local',
  'development. Set OCR_SERVICE_URL and unset USE_MOCK_OCR to hit the',
  'real OCR microservice.',
].join('\n');

export class OCRMockAdapter implements IOCRPort {
  private readonly jobs = new Map<string, MockJob>();

  async startJob(
    _file: Uint8Array,
    fileName: string,
  ): Promise<OCRJobHandle> {
    const jobId = `mock-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    this.jobs.set(jobId, { fileName, startedAt: Date.now() });
    console.log(`[ocr-mock] startJob: ${jobId} (${fileName})`);
    return {
      jobId,
      fileName,
      estimatedTimeMs: PENDING_DURATION_MS + PROCESSING_DURATION_MS,
    };
  }

  async getJobStatus(jobId: string): Promise<OCRJobStatus> {
    const job = this.jobs.get(jobId);
    if (!job) {
      throw new OCRServiceError(`Unknown mock OCR job: ${jobId}`, 404);
    }

    const elapsed = Date.now() - job.startedAt;
    if (elapsed < PENDING_DURATION_MS) return { status: 'PENDING' };
    if (elapsed < PENDING_DURATION_MS + PROCESSING_DURATION_MS) {
      return { status: 'PROCESSING' };
    }
    return { status: 'COMPLETED' };
  }

  async getJobResult(jobId: string): Promise<OCRResult> {
    const job = this.jobs.get(jobId);
    if (!job) {
      throw new OCRServiceError(`Unknown mock OCR job: ${jobId}`, 404);
    }

    const status = await this.getJobStatus(jobId);
    if (status.status !== 'COMPLETED') {
      throw new OCRServiceError(
        `Mock OCR job ${jobId} is not complete (status: ${status.status}).`,
      );
    }

    return {
      pageCount: 1,
      pages: [
        {
          pageNumber: 1,
          text: MOCK_FULL_TEXT,
          confidence: 0.95,
        },
      ],
      fullText: MOCK_FULL_TEXT,
    };
  }
}
